Add cluster-autoscaler
giantswarm/default-apps-eks pull request #58
Opened 2023-12-18 13:33 UTC by paurosello

### What this PR does / why we need it

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

2023-12-18 13:33 UTC, paurosello commented
/run cluster-test-suites

2024-01-02 16:04 UTC, AndiDog approved these changes

2024-01-11 16:52 UTC, calvix commented
@paurosello why is aws pod identity webhook needed? AFAIK EKS provide this feature out of the box

2024-01-12 07:53 UTC, calvix commented on helm/default-apps-eks/values.yaml
> +    version: 1.13.2
Why do we need aws-pod-identity-webhook

2024-01-12 07:54 UTC, calvix requested changes
not sure about the aws-pod-identity-webhook

2024-01-15 18:45 UTC, weseven commented
@calvix @paurosello I've tested the autoscaler without aws-pod-identity-webhook, it works correctly (both scale up and scale down).

Pending your reviews, this is ready to be merged.

2024-01-16 08:01 UTC, calvix approved these changes

2024-01-16 11:21 UTC, merged