Teleport kube agent
giantswarm/default-apps-eks pull request #74
Opened 2024-01-24 15:24 UTC by ssyno

### What this PR does / why we need it

### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

2024-01-25 14:19 UTC, ssyno commented
/run cluster-test-suites

2024-02-15 10:18 UTC, AndiDog requested changes

2024-02-15 10:18 UTC, AndiDog commented on helm/default-apps-eks/values.yaml
> +  coreDNS:
We already install [coredns in the cluster chart](https://github.com/giantswarm/cluster-eks/blob/main/helm/cluster-eks/templates/coredns-helmrelease.yaml)

2024-02-15 10:22 UTC, ssyno commented on helm/default-apps-eks/values.yaml
> +  coreDNS:
oh nice, I will remove it, what about its configuration?

2024-02-15 10:42 UTC, ssyno commented
/run cluster-test-suites

2024-02-15 13:39 UTC, tuladhar approved these changes

2024-02-19 11:04 UTC, AndiDog commented on helm/default-apps-eks/templates/apps.yaml
> +  {{- if .extraConfigs }}
Let's make this consistent with default-apps-aws where we support the `priority` feature as of a customer request.

See https://github.com/giantswarm/default-apps-aws/blob/d7a1dd710447356920767d7f7d9a44b55be1af38/helm/default-apps-aws/templates/apps.yaml#L54-L63 (but use correctly-spelled `priority`, not `priotity` – that's to be fixed over there).

2024-02-19 11:04 UTC, AndiDog commented on helm/default-apps-eks/values.yaml
> +        name: "{{ $.Values.clusterName }}-teleport-kube-agent-config"
Please document here where the config comes from (seems to be externally introduced, I guess by an operator).

2024-02-19 15:04 UTC, ssyno commented on helm/default-apps-eks/templates/apps.yaml
> +  {{- if .extraConfigs }}
sure, updating itnow

2024-02-19 15:15 UTC, ssyno commented on helm/default-apps-eks/values.yaml
> +        name: "{{ $.Values.clusterName }}-teleport-kube-agent-config"
Added comment

2024-02-20 10:02 UTC, calvix approved these changes

2024-02-20 12:24 UTC, AndiDog reviewed
Please go ahead and merge once the `priotity` typo is fixed

2024-02-20 12:24 UTC, AndiDog approved these changes

2024-02-20 12:41 UTC, merged